version: "3.8"
services:
  genie:
    image: netflixoss/genie-app:4.0.0-rc.75
    ports:
      - "8080:8080"
    depends_on:
      - genie-hadoop-prod
      - genie-hadoop-test
      - genie-apache
      - genie-presto
    tty: true
    container_name: genie_demo_app_4.0.0-rc.75
  genie-apache:
    image: netflixoss/genie-demo-apache:4.0.0-rc.75
    tty: true
    container_name: genie_demo_apache_4.0.0-rc.75
  genie-client:
    image: netflixoss/genie-demo-client:4.0.0-rc.75
    depends_on:
      - genie
    tty: true
    container_name: genie_demo_client_4.0.0-rc.75
  genie-hadoop-prod:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
      - "8042:8042"
    tty: true
    container_name: genie_demo_hadoop_prod_4.0.0-rc.75
  genie-hadoop-test:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19889:19888"
      - "50071:50070"
      - "50076:50075"
      - "8089:8088"
      - "8043:8042"
    tty: true
    container_name: genie_demo_hadoop_test_4.0.0-rc.75
  genie-presto:
    image: prestosql/presto:337
    ports:
      - "9090:8080"
    tty: true
    container_name: genie_demo_presto_4.0.0-rc.75
