dist: xenial
addons:
  postgresql: '9.6'
language: java
jdk:
- openjdk8
services:
- mysql
- postgresql
- docker
git:
  depth: 3
install: "./travis/installViaTravis.sh"
before_script:
- cat "$TRAVIS_BUILD_DIR/travis/config/mysql/my.cnf" | sudo tee -a /etc/mysql/my.cnf
- sudo service mysql restart
- mysql -u root -e 'create database genie;'
- psql  -U postgres -c 'create database genie;'
script: "./travis/buildViaTravis.sh"
before_cache:
- rm -f  "${HOME}/.gradle/caches/modules-2/modules-2.lock"
- rm -fr "${HOME}/.gradle/caches/*/plugin-resolution/"
- rm -f  "${HOME}/.gradle/caches/*/fileHashes/fileHashes.bin"
- rm -f  "${HOME}/.gradle/caches/*/fileHashes/fileHashes.lock"
cache:
  directories:
  - "${HOME}/.gradle/caches/"
  - "${HOME}/.gradle/wrapper/"
  - genie-ui/node_modules/
  - genie-ui/.gradle/nodejs
  - genie-ui/.gradle/npm
  timeout: 1000
env:
  global:
  - secure: a5QmXCWR7wwEf/poWSj3PDAb6VICKqTTw3qbNjQwSvCzaCYtZZmxLbruQQlKOyR6W4j2VMrp2Ip5xrBjlCrOTvkFymPY3L+EwbPxsXbO4uhzs43BNFLhDon/Duv3TRhnedkqP0s8hN1ylxCbcID0UUPXQGrhnu8mb5QlDUx2mr8=
  - secure: OU4bxS0wlL7cu2w+rlDNheW8qQxduBZfXqFkTf80Ds6QDpYK3cDi4DrazqGM9afzy5CwwJtesICIhU4rFKGyOp7D4B8caHAnoefhtOt5RAhj7cuR0N9ub0GGtHAWfZFJXnCOrLyZHpS5GgCNtR7vH6TJ3N4xxZM/JUDphNQz7b4=
  - secure: KhF71cR3Goh37T91P1peQIo2fyqAy/+LwicVulgqx1KLIC0Dp+npIDAI+LCuAMdgEwzJSxAVmf1KRCFm0TNSX0dk0MH9uWSENWvqfYWalGCT548yQ0r6ZmUWj7XVZWlNwaO3RYtn7G03digsWIilkb8Z08wRMfUEFz0ME7+Ri68=
  - secure: AdibGk6647I6bTxbRFYEAthBoQslFsxgTejD8+ru4rTZDmmy4aXx1ZgHFNjzFkKrOyrMHh/KCucbhTIHOaTljWupV4AeWDk0t3gkBJDpN8UcmR+hlgwwGMc4pfKtJiyE6p43QnHQ4p3GZh6+Wsb46OO3gJKQYh8GTiouiDrJgq8=
  - secure: S5xjLuMEd/dkWHCRKwYP1frBNXSO2u9zC+zVq6i+ctEniAU29N4c2b+xGSKeWpfiPgW8aYiHNYUQxuizSH4ddTogZ799T53zT1GAdWDGmACzhwPvSs0N3NYQmeqnwCzGydoa61E8ARWIfa88rxN9vrSWnAM9AsGw1oSuXbAKrWc=
  - secure: eGKKPIZv9p0ZdHnOkIaUBRkwQXIomVJPw+hskpU/13gTr2Y2GsNqiFg5B3TC8QZxqj4Y2W2btVBO/VewEL2furfaV1LJC0l1irhNzo5/yz1nOFRRgXEsj+0QZnqLGhK5WBG3j8AVX8YG1WtVd5oO46MVHpJm+kI2OjYTEGvjq8c=
  - secure: EdgBnr/MQCTd/2ywBXUlQKGnXBcof2iAuuzou1RtC+9MPOJB9O/C0Sss7t94TdUd64WWYHPeFG+IDDSP4x6CgdpxbPzoYx015HUWEuBB2AUqWBc9gp2yHNy7eL59xLBYsr2vwbXjkStPeQ37XvPjvql1OzKbBO5ZJ4cxoS7QuSU=
  - secure: PSapinCw6NBedXgctnXBX3Z9GpS8cUdFcXr7NdRUpboHpcVs3oT/Xf7GKbmi5gb09ZoEZjOny0sMrzfxl1Zpd9Qt/pMc//EJQlFue8PJLjOhGpcoO8Ta7fvPJj5YMKO3CidN+JVfIduKH2w+wcFKIjeHPp+jl7V0GeOJOyg1nHg=
  - secure: UbFKySlHTtFuHgEDeEJLwxia8kh1S/ABYR+U3DqmR8xU3EoxeaLC1UgVHikA4BTMY2yTEE/sISZN27TUzg4vPjV2MapNwcnmMV5fS5U7o8foZ1DOCGbNss3bxl8kgXV1eIE68lKGJPgFwgzP7i57Ku86cQu7714as03UEnjX9yg=
notifications:
  slack:
    secure: H5nS+GX6TYTU27ur6YFG5OgrQeUbzXLok5ub6+xcmyYEeVPpnQ1Gg/wKqTAGsP9j6tAkqPpxgYT9i9Do6eyTEplK6bTvQVyhilsEDtxGJbUO8XOE9TSo6jAe/lD3EB5l46gxFID+Hg9IkPii4LwEabP7PVehrB1JfNZ6QDgSRRM=
